### ISSUE TITLE
ArgumentError: invalid byte sequence in US-ASCII when copying from clipboard

### ISSUE THREAD

**Issue by mazuhl** [chef-boneyard/win32-clipboard#1]
If I have the following copied into my Windows clipboard: `Hello world, £12 is the cost` and I try to access the clipboard:

``` ruby
require 'rubygems'
require 'win32/clipboard'
include Win32

c = Clipboard.data
```

... I get an `ArgumentError: invalid byte sequence in US-ASCII` from line 123 in `clipboard.rb` caused by using the pound symbol. If I try force the clipboard to read as Unicode it gives the same error. Is there a way to read in these characters/the full clipboard?

I'm using the following:
- Windows XP
- Ruby 1.9.2p180 (2011-02-18)
- win32/clipboard 0.5.2

**Comment by djberg96** [comment]
I tested this in the ffi branch and it works fine, so your issue will be addressed once 0.6.0 is released, which should be soon.
