### ISSUE TITLE
require fails on linux

### ISSUE THREAD

**Issue by thisismydesign** [chef-boneyard/win32-clipboard#12]
Even though it's a gem for windows there're use cases for it not to fail on other systems (e.g. using linux CI or dev env)

The error is the following:
```
/home/travis/.rvm/gems/ruby-2.3.3/gems/ffi-1.9.18/lib/ffi/types.rb:69:in `find_type': unable to resolve type 'uintptr_t' (TypeError)
	from /home/travis/.rvm/gems/ruby-2.3.3/gems/ffi-1.9.18/lib/ffi/library.rb:446:in `typedef'
	from /home/travis/.rvm/gems/ruby-2.3.3/gems/win32-clipboard-0.6.4/lib/win32/windows/functions.rb:7:in `<module:Functions>'
	from /home/travis/.rvm/gems/ruby-2.3.3/gems/win32-clipboard-0.6.4/lib/win32/windows/functions.rb:4:in `<module:Windows>'
	from /home/travis/.rvm/gems/ruby-2.3.3/gems/win32-clipboard-0.6.4/lib/win32/windows/functions.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.3.3/gems/win32-clipboard-0.6.4/lib/win32/clipboard.rb:3:in `require_relative'
	from /home/travis/.rvm/gems/ruby-2.3.3/gems/win32-clipboard-0.6.4/lib/win32/clipboard.rb:3:in `<top (required)>'
	from /home/travis/build/thisismydesign/poe-sniper/lib/poe/sniper/alert.rb:2:in `require'
```

As a [workaround](http://stackoverflow.com/questions/4871309/what-is-the-correct-way-to-detect-if-ruby-is-running-on-windows) I'm currently checking the OS with
`Gem.win_platform?`

But I think it'd be nicer if the gem did this check and would raise it's own exception - or even better it would do nothing.

Let me know what you think.

Thanks,
Csaba

**Comment by djberg96** [comment]
I think this is a job for your configuration/Gemfile/whatever.

**Comment by thisismydesign** [comment]
At the very least you should consider failing meaningfully. Nevertheless I see no point in polluting the code every time someone wants to use a CI system when this could be taken care of by the gem.
