### ISSUE TITLE
Exception on load

### ISSUE THREAD

**Issue by orgads** [chef-boneyard/win32-clipboard#4]
Windows 7, win32-clipboard 0.6.0.

irb(main):001:0> require 'win32/clipboard'
FFI::NotFoundError: Function 'GetWindowLongPtrA' not found in [user32.dll]
        from D:/Ruby/lib/ruby/gems/2.0.0/gems/ffi-1.9.3-x86-mingw32/lib/ffi/library.rb:261:in `attach_function'
        from D:/Ruby/lib/ruby/gems/2.0.0/gems/win32-clipboard-0.6.0/lib/win32/windows/functions.rb:36:in`module:Functions'
        from D:/Ruby/lib/ruby/gems/2.0.0/gems/win32-clipboard-0.6.0/lib/win32/windows/functions.rb:4:in `<module:Windows>'
        from D:/Ruby/lib/ruby/gems/2.0.0/gems/win32-clipboard-0.6.0/lib/win32/windows/functions.rb:3:in`<top (required)>'
        from D:/Ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from D:/Ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in`require'
        from D:/Ruby/lib/ruby/gems/2.0.0/gems/win32-clipboard-0.6.0/lib/win32/clipboard.rb:3:in `<top (required)>'
        from D:/Ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in`require'
        from D:/Ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in `rescue in require'
        from D:/Ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:124:in`require'
        from (irb):1
        from D:/Ruby/bin/irb:12:in `<main>'

**Comment by djberg96** [comment]
It turns out that function is only exported on a 64-bit runtime, even though the docs say it can be used for either 32 or 64 bit. I updated the code to use GetWindowLong and SetWindowLong if GetWindowLongPtr and SetWindowLongPtr cannot be found.

I've already fixed the code and pushed out a new release. Thanks for the report!
